spring:
  application:
    name: legalcontract

server:
  port: 9000
  connection-timeout: 50000 # Timeout in milliseconds
  servlet:
    session:
      timeout: 50000ms # Timeout in milliseconds
  tomcat:
    connection-timeout: 50000 # Timeout in milliseconds
